
POST http://localhost:3000/api/transaction/create HTTP/1.1
content-type: application/json

{
    "amount": 133,
    "file": "test file",
    "name": "test fuer nicht existenten user",

    "category": "bevarage",
    "user": "1"
}
