POST http://localhost:3000/api/user/create HTTP/1.1
content-type: application/json

{
    "firstName": "max zwei",
    "lastName": "Maxus",
    "mail": "max-maxus@zweiteruser.de",
    "password": "123456"
}
